-- MEMBOARD
drop table board;
create table member(
    MEMID       NVARCHAR2(20) PRIMARY KEY,
    MEMPW       NVARCHAR2(100),
    MEMNAME     NVARCHAR2(5),
    MEMBIRTH    NVARCHAR2(10),
    MEMGENDER   NVARCHAR2(2),
    MEMEMAIL    NVARCHAR2(30),
    MEMPHONE    NVARCHAR2(20),
    MEMADDR     NVARCHAR2(100),
    MEMPROFILENAME  NVARCHAR2(50)
);

DROP TABLE MEMBER;

commit;

SELECT * FROM MEMBER;




drop view boardlist;



CREATE TABLE BOARD(
    BONUM        NUMBER PRIMARY KEY,
    BOWRITER     NVARCHAR2(20),
    BOTITLE      NVARCHAR2(50),
    BOCONTENT    NVARCHAR2(500),
    BODATE       DATE,
    BOHIT        NUMBER,
    BOFILENAME   NVARCHAR2(50)
);

CREATE SEQUENCE BO_SEQ INCREMENT BY 1;
drop sequence bo_seq;


CREATE VIEW BOARDLIST AS 
SELECT BOARD.*, ROW_NUMBER() OVER(ORDER BY BONUM DESC) AS RN
FROM BOARD;




CREATE TABLE COMMENTS(
    CMTNUM      NUMBER,
    CBNUM       NUMBER, 
    CMTWRITER   NVARCHAR2(20),
    CMTCONTENT  NVARCHAR2(100),
    CMTDATE     DATE,
    CONSTRAINT CMT_PK PRIMARY KEY(CMTNUM, CBNUM),
    CONSTRAINT CMT_FK_CBNUM FOREIGN KEY(CBNUM) REFERENCES BOARD(BONUM),
    CONSTRAINT CMT_FK_CMTWRITER FOREIGN KEY(CMTWRITER) REFERENCES MEMBER(MEMID)
);



COMMIT;

select * from comments;



-- ´ñ±Û SEQ»ý¼º
CREATE SEQUENCE CMT_SEQ INCREMENT BY 1 START WITH 1;
drop SEQUENCE cmt_seq;

